name: Compile Test for icon-2.1.0

on:
    push:
        paths:
            - '!docs/**'
            - '!README.md'
            - 'src/**'
            - 'tests/**'
            - 'configs/machines/ollie.yaml'
            - 'configs/components/icon/*.yaml'

jobs:
    call-workflow:
        uses: esm-tools/esm_tools/.github/workflows/esm_tools_actions_hpc_awi_ollie.yml@monorepo_ci_test
        with:
            model_name: icon
            model_version: 2.1.0