name: Compile Test for recom-2.0-r

on:
    push:
        paths:
            - '!docs/**'
            - '!README.md'
            - 'src/**'
            - 'tests/**'
            - 'configs/machines/ollie.yaml'
            - 'configs/components/recom/*.yaml'

jobs:
    call-workflow:
        uses: esm-tools/esm_tools/.github/workflows/esm_tools_actions_hpc_awi_ollie.yml
        with:
            model_name: recom
            model_version: 2.0-r