fc: mpif90
f77: mpif90
mpifc: mpif90
#mpifc: mpigcc
mpicc: mpigxx
cc: mpigcc
cxx: mpigxx

module_actions:
        - "load gnu.compiler/6.3.0"
        - "unload intel.compiler intel.mpi && module load intel.mpi"
        - "unload netcdf/4.6.2_intel"
        - "load netcdf/4.6.2_gnu"
        #- "unload automake"
