model: esm-interface

metadata:
        Institute: Alfred Wegener Institute
        Description: Coupling interface for a modular coupling approach of ESMs.
        Authors: Nadine Wieters (nadine.wieters@awi.de)
        Publications: None
        License: None

available_versions:
- '1.0'
- yac
choose_version:
  '1.0':
    branch: dev_prototype_awicm
    comp_command: mkdir -p build; cd build; cmake ..; make -j `nproc --all`
  yac:
    branch: include_yac
    comp_command: mkdir -p build; cd build; cmake ..; make -j `nproc --all`
comp_command: ${default.comp_command}
destination: esm-interface
git-repository: https://gitlab.dkrz.de/modular_esm/esm-interfaces.git
