available_versions:
- agrif
- '2.0'
choose_version:
  '2.0':
    couplings:
    - nemo-ORCA05_LIM2_KCM_AOW_FS_OASISMCT4+oifs43r3-foci
  agrif:
    couplings:
    - nemo-ORCA05_LIM2_KCM_AGRIF_OASISMCT4+oifs43r3-foci
