available_versions:
- 1.2.00p4
- 1.2.01
- 1.2.01p1
choose_version:
  1.2.00p4:
    couplings:
    - mpiom-1.6.2p3+echam-6.3.02p4
  1.2.01:
    couplings:
    - mpiom-1.6.3+echam-6.3.04p1
  1.2.01p1:
    couplings:
    - mpiom-1.6.3p2+echam-6.3.05p2
