jobs:
  install_as_user:
    runs-on:
    - self-hosted
    - ollie
    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      run: 'module purge

        module load git

        module load python3

        '
    - name: Check versions and env
      run: 'git --version

        python --version

        pip --version

        env

        '
    - name: Install project
      run: ./install.sh
    - name: Check binaries
      run: 'export PATH=${HOME}/.local/bin:${PATH}

        which esm_master

        which esm_runscripts

        which esm_versions

        '
  install_models:
    needs: install_as_user
    runs-on:
    - self-hosted
    - ollie
    steps:
    - name: Install Model
      run: 'export PATH=${HOME}/.local/bin:${PATH}

        which esm_master

        esm_master --version

        rm -rf /work/ollie/pgierz/esm_tools_ollie_ci/${{ matrix.model }}/model_sources

        mkdir -p /work/ollie/pgierz/esm_tools_ollie_ci/${{ matrix.model }}/model_sources

        cd /work/ollie/pgierz/esm_tools_ollie_ci/${{ matrix.model }}/model_sources/

        esm_master install-${{ matrix.model }}

        '
    strategy:
      fail-fast: false
      matrix:
        model:
        - fesom_mesh_part-1.4
        - fesom_mesh_part-2.0
name: CI-Ollie-install-fesom-mesh-part
'on':
  pull_request:
    branches:
    - release
    - develop
    - '*prep-release*'
    paths:
    - configs/esm_master/components/fesom_mesh_part.yaml
  push:
    branches:
    - release
    - develop
    - '*prep-release*'
    - '*hotfix*'
    paths:
    - configs/esm_master/components/fesom_mesh_part.yaml
