hist_fold: hist_harvest
hist_scenario: ssp370  # dataset to use for year > 2014

input_sources:
        lctlib: "${echam.model_dir}/lctlib_nlct21.def"
        "jsbach_1850": "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_5layers_1850${jsbachnc_file_ending}.nc"
        "jsbach_1976": "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_5layers_1850${jsbachnc_file_ending}.nc"

        # FOCI specific input sources
        "cpools_foci": "${adj_input_dir}/cpools_${echam.resolution}${echam.ocean_resolution}_pdv0002_51251231.nc"
        "npools_foci": "${adj_input_dir}/cpools_${echam.resolution}${echam.ocean_resolution}_pdv0002_51251231.nc"
        "fpc_foci": "${adj_input_dir}/cpools_${echam.resolution}${echam.ocean_resolution}_pdv0002_51251231.nc"
        "lctlib_foci": "${computer.pool_directories.focipool}/ECHAM6_GENERAL/JSBACH/input/lctlib_nlct21.def"

forcing_sources:
        # harvest
        "LU_1850": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1850.nc"
        "LU_1950": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1950.nc"
        "LU_HIST":
                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1850.nc":
                        to: 1850
                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_@YEAR@.nc":
                        from: 1851
                        to: 2014
                # HIST scenario will use this data beyond year 2014
                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_scenario}_harvest/LUH_harvest_${echam.resolution}_@YEAR@.nc":
                        from: 2015
        # landuse transitions
        "LU_trans_none": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/no_LUH_transitions_${echam.resolution}.nc"
        "LU_trans_time":
            "${input_dir}/${echam.resolution}/New_Hampshire_LCC/hist${jsbachnc_file_ending}/LUH_scaled_transitions_${echam.resolution}_@YEAR@.nc":
                to: 2014
            # For the transient land data use a similar fix like in HIST land use
            "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_scenario}${jsbachnc_file_ending}/LUH_scaled_transitions_${echam.resolution}_@YEAR@.nc":
                from: 2015
        "LU_trans_ssp585":
            "${input_dir}/${echam.resolution}/New_Hampshire_LCC/ssp585${jsbachnc_file_ending}/LUH_scaled_transitions_${echam.resolution}_@YEAR@.nc":
                from: 2015
                to: 2299

choose_dataset:
        r0007:
                "hist_fold": "hist"
                add_forcing_sources:
                        "LU_RCP26":
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1850.nc":
                                        to: 1850
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_@YEAR@.nc":
                                        from: 1851
                                        to: 2014
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/rcp26/LUH_harvest_${echam.resolution}_rcp26_@YEAR@.nc":
                                        from: 2015
                        "LU_RCP45":
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1850.nc":
                                        to: 1850
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_@YEAR@.nc":
                                        from: 1851
                                        to: 2014
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/rcp45/LUH_harvest_${echam.resolution}_rcp45_@YEAR@.nc":
                                        from: 2015
                        "LU_RCP85":
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1850.nc":
                                        to: 1850
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_@YEAR@.nc":
                                        from: 1851
                                        to: 2014
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/rcp85/LUH_harvest_${echam.resolution}_rcp85_@YEAR@.nc":
                                        from: 2015
                        "cover_fract_HIST":
                                "${cover_fract_dir}/cover_fract_${echam.resolution}${echam.ocean_resolution}_11tiles_1850.nc":
                                        to: 1850
                                "${cover_fract_dir}/cover_fract_${echam.resolution}${echam.ocean_resolution}_11tiles_@YEAR@.nc":
                                        from: 1851
        r0009:
                add_forcing_sources:
                        "Ndepo_1850": "${input_dir}/${echam.resolution}/${echam.resolution}_ndepo_CMIP_NCAR_CCMI-1-0_gr_185001-185012-clim.nc"
                        "a_nd_file": "${input_dir}/${echam.resolution}/spitfire/a_nd_${echam.resolution}.nc"
                        "lightning": "${input_dir}/${echam.resolution}/spitfire/LISOTD_HRMC_V2.2_${echam.resolution}.nc"
                        "popdens":   "${input_dir}/${echam.resolution}/spitfire/population_density_HYDE_${echam.resolution}.nc"
                        "cover_fract_HIST":
                                "${cover_fract_dir}/cover_fract_${echam.resolution}${echam.ocean_resolution}_11tiles_1850.nc":
                                        to: 1850
                                "${cover_fract_dir}/cover_fract_${echam.resolution}${echam.ocean_resolution}_11tiles_@YEAR@.nc":
                                        from: 1851
        r0010:
                add_forcing_sources:
                        "Ndepo_1850": "${input_dir}/${echam.resolution}/${echam.resolution}_ndepo_CMIP_NCAR_CCMI-1-0_gr_185001-185012-clim.nc"
                        "a_nd_file": "${input_dir}/${echam.resolution}/spitfire/a_nd_${echam.resolution}.nc"
                        "lightning": "${input_dir}/${echam.resolution}/spitfire/LISOTD_HRMC_V2.2_${echam.resolution}.nc"
                        "popdens":   "${input_dir}/${echam.resolution}/spitfire/population_density_HYDE_${echam.resolution}.nc"
                        "cover_fract_HIST":
                                "${cover_fract_dir}/cover_fract_${echam.resolution}_11tiles_1850.nc":
                                        to: 1850
                                "${cover_fract_dir}/cover_fract_${echam.resolution}_11tiles_@YEAR@.nc":
                                        from: 1851
                        "cover_fract_SSP585":
                                "${cover_fract_dir}/cover_fract_${echam.resolution}_11tiles_1850.nc":
                                        to: 2014
                                "${input_dir}/${echam.resolution}/land_use_maps/ssp585/cover_fract_${echam.resolution}_11tiles_@YEAR@.nc":
                                        from: 2015
                                        to: 2300

