hist_fold: hist_harvest
hist_scenario: ssp370  # dataset to use for year > 2014

input_sources:
        lctlib: "${echam.model_dir}/lctlib_nlct21.def"
        "jsbach_1850": "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_5layers_1850${jsbachnc_file_ending}.nc"
        "jsbach_1976": "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_5layers_1976${jsbachnc_file_ending}.nc"

        # FOCI specific input sources
        "cpools_foci": "${adj_input_dir}/cpools_${echam.resolution}${echam.ocean_resolution}_pdv0002_51251231.nc"
        "npools_foci": "${adj_input_dir}/cpools_${echam.resolution}${echam.ocean_resolution}_pdv0002_51251231.nc"
        "fpc_foci": "${adj_input_dir}/cpools_${echam.resolution}${echam.ocean_resolution}_pdv0002_51251231.nc"
        "lctlib_foci": "${computer.pool_directories.focipool}/ECHAM6_GENERAL/JSBACH/input/lctlib_nlct21.def"

forcing_sources:
        # harvest
        "LU_1850": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1850.nc"
        "LU_1950": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1950.nc"
        "LU_HIST":
                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1850.nc":
                        to: 1850
                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_@YEAR@.nc":
                        from: 1851
                        to: 2014
                # HIST scenario will use this data beyond year 2014
                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_scenario}_harvest/LUH_harvest_${echam.resolution}_@YEAR@.nc":
                        from: 2015

        # landuse transitions
        "LU_trans_none": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/no_LUH_transitions_${echam.resolution}.nc"
        "LU_trans_1850": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/hist${jsbachnc_file_ending}/LUH_scaled_transitions_${echam.resolution}_1850.nc"
        "LU_trans_hist":
            "${input_dir}/${echam.resolution}/New_Hampshire_LCC/hist${jsbachnc_file_ending}/LUH_scaled_transitions_${echam.resolution}_@YEAR@.nc":
                to: 2014
            # For the transient land data use a similar fix like in HIST land use
            "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_scenario}${jsbachnc_file_ending}/LUH_scaled_transitions_${echam.resolution}_@YEAR@.nc":
                from: 2015

        # NOTE: these files are prepared by Christopher Danek (AWI). These are 
        # yearly files where each file contain monthly data
        Ndepo_ssp: 
                # These files are 12-monthly; see README.md in Ndepo/ directory
                # NOTE: ssp370 might be missing in this directory
                "${input_dir_awi}/${echam.resolution}/Ndepo/${echam.scenario}/${echam.resolution}_ndepo.input4MIPs_surfaceFluxes_ScenarioMIP-NCAR-CCMI-${echam.scenario}_@YEAR@.nc": 
                    from: 1850
                    to: 2099
                "${input_dir_awi}/${echam.resolution}/Ndepo/${echam.scenario}/${echam.resolution}_ndepo.input4MIPs_surfaceFluxes_ScenarioMIP-NCAR-CCMI-${echam.scenario}_2099.nc":
                    from: 2100
                    to: 2101

choose_dataset:
        r0007:
                hist_fold: "hist"
                add_forcing_sources:
                        "cover_fract_HIST":
                                "${cover_fract_dir}/cover_fract_${echam.resolution}${echam.ocean_resolution}_11tiles_1850.nc":
                                        to: 1850
                                "${cover_fract_dir}/cover_fract_${echam.resolution}${echam.ocean_resolution}_11tiles_@YEAR@.nc":
                                        from: 1851
        r0009:
                add_forcing_sources:
                        "Ndepo_1850": "${input_dir}/${echam.resolution}/${echam.resolution}_ndepo_CMIP_NCAR_CCMI-1-0_gr_185001-185012-clim.nc"
                        "a_nd_file": "${input_dir}/${echam.resolution}/spitfire/a_nd_${echam.resolution}.nc"
                        "lightning": "${input_dir}/${echam.resolution}/spitfire/LISOTD_HRMC_V2.2_${echam.resolution}.nc"
                        "popdens":   "${input_dir}/${echam.resolution}/spitfire/population_density_HYDE_${echam.resolution}.nc"
                        "cover_fract_HIST":
                                "${cover_fract_dir}/cover_fract_${echam.resolution}${echam.ocean_resolution}_11tiles_1850.nc":
                                        to: 1850
                                "${cover_fract_dir}/cover_fract_${echam.resolution}${echam.ocean_resolution}_11tiles_@YEAR@.nc":
                                        from: 1851
        r0010:
                add_forcing_sources:
                        "Ndepo_1850": "${input_dir}/${echam.resolution}/${echam.resolution}_ndepo_CMIP_NCAR_CCMI-1-0_gr_185001-185012-clim.nc" # 12 months
                        "Ndepo_1950": "${input_dir}/${echam.resolution}/ndepo/Ndepo.1950.nc"

                        "Ndepo_hist_scenario":
                        # TODO: pool on Levante seems to be broken currently.
                        # There are no yearly Ndepo files. ${input_dir_awi}
                        # contains the yearly files
                                "${input_dir}/${echam.resolution}/ndepo/Ndepo.1850.nc":
                                        to: 1850
                                "${input_dir}/${echam.resolution}/ndepo/Ndepo.@YEAR@.nc":
                                        from: 1851
                                        to: 2014
                                # TODO: these files don't exist on Levante
                                "${input_dir}/${echam.resolution}/ndepo/Ndepo_${echam.scenario}.@YEAR@.nc":
                                        from: 2015

                        "a_nd_file": "${input_dir}/${echam.resolution}/spitfire/a_nd_${echam.resolution}.nc"
                        "lightning": "${input_dir}/${echam.resolution}/spitfire/LISOTD_HRMC_V2.2_${echam.resolution}.nc"
                        "popdens": "${input_dir}/${echam.resolution}/spitfire/population_density_HYDE_${echam.resolution}.nc" # ndecades
                        "popdens_ssp1":
                                #"${input_dir}/${echam.resolution}/spitfire/population_density_ssp1_${echam.resolution}.nc": # nyear
                                "${input_dir_awi}/${echam.resolution}/spitfire/population_density_ssp1_T63.nc": # see README.md in this dir
                                        from: 1850
                                        to: 2100
                        "popdens_ssp2":
                                #"${input_dir}/${echam.resolution}/spitfire/population_density_ssp2_${echam.resolution}.nc": # nyear
                                "${input_dir_awi}/${echam.resolution}/spitfire/population_density_ssp2_T63.nc": # see README.md in this dir
                                        from: 1850
                                        to: 2100
                        "popdens_ssp5":
                                #"${input_dir}/${echam.resolution}/spitfire/population_density_ssp5_${echam.resolution}.nc": # nyear
                                "${input_dir_awi}/${echam.resolution}/spitfire/population_density_ssp5_T63.nc": # see README.md in this dir
                                        from: 1850
                                        to: 2100
                        "cover_fract_HIST":
                                "${cover_fract_dir}/cover_fract_${echam.resolution}_11tiles_1850.nc":
                                        to: 1850
                                "${cover_fract_dir}/cover_fract_${echam.resolution}_11tiles_@YEAR@.nc":
                                        from: 1851
                        "cover_fract_hist_scenario":
                                "${cover_fract_dir}/cover_fract_11tiles_1850.nc":
                                        to: 1850
                                "${cover_fract_dir}/cover_fract_11tiles_@YEAR@.nc":
                                        from: 1851
                                        to: 2014
                                "${cover_fract_dir}/${echam.scenario}/cover_fract_11tiles_@YEAR@.nc":
                                        from: 2015
                        "LU_trans_hist_scenario": 
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/hist${dynveg}/LUH_scaled_transitions_${echam.resolution}_@YEAR@.nc": 
                                        to: 2014
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${echam.scenario}${dynveg}/LUH_scaled_transitions_${echam.resolution}_@YEAR@.nc": 
                                        from: 2015
                        "cover_fract_ssp126":
                                "${cover_fract_dir}/cover_fract_${echam.resolution}_11tiles_1850.nc":
                                        to: 2014
                                "${input_dir}/${echam.resolution}/land_use_maps/ssp126/cover_fract_${echam.resolution}_11tiles_@YEAR@.nc":
                                        from: 2015
                                        to: 2300
                        "cover_fract_ssp245":
                                "${cover_fract_dir}/cover_fract_${echam.resolution}_11tiles_1850.nc":
                                        to: 2014
                                "${input_dir}/${echam.resolution}/land_use_maps/ssp245/cover_fract_${echam.resolution}_11tiles_@YEAR@.nc":
                                        from: 2015
                                        to: 2300
                        "cover_fract_ssp534os":
                                "${cover_fract_dir}/cover_fract_${echam.resolution}_11tiles_1850.nc":
                                        to: 2014
                                "${input_dir}/${echam.resolution}/land_use_maps/ssp534os/cover_fract_${echam.resolution}_11tiles_@YEAR@.nc":
                                        from: 2015
                                        to: 2300
                        "cover_fract_ssp585":
                                "${cover_fract_dir}/cover_fract_${echam.resolution}_11tiles_1850.nc":
                                        to: 2014
                                "${input_dir}/${echam.resolution}/land_use_maps/ssp585/cover_fract_${echam.resolution}_11tiles_@YEAR@.nc":
                                        from: 2015
                                        to: 2300

                        "LU_hist_scenario":
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/hist_harvest/LUH_harvest_${echam.resolution}_1850.nc":
                                        to: 1850
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/hist_harvest/LUH_harvest_${echam.resolution}_@YEAR@.nc":
                                        from: 1851
                                        to: 2014
                                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${echam.scenario}_harvest/LUH_harvest_${echam.resolution}_@YEAR@.nc":
                                        from: 2015
