available_versions:
  - '2.0'
  - 2.0-r
  - 2.0-recom-awicm
choose_version:
  '2.0':
    branch: oxygen
  2.0-r:
    # OG: This will be the master branch for fesom-recom-2.0. We rename it later.
    branch: recom-update
  2.0-recom-awicm:
    branch: co2_coupling
clean_command: ${defaults.clean_command}
comp_command: mkdir -p build; cd build; cmake ..;  make -j `nproc --all`
destination: recom
git-repository: https://gitlab.dkrz.de/modular_esm/recom.git
install_libs:
  - build/librecom.a
