# THE aleph.iccp.kr YAML config file

name: aleph

accounting: true
batch_system: "pbs"

operating_system: "SLES"

jobtype: compute
sh_interpreter: "/bin/sh"


choose_jobtype:
        post:
                partition: serial
        compute:
                partition: iccp
        tidy_and_resubmit:
                partition: iccp

choose_partition:
        "iccp":
                cores_per_node: 40
        "serial":
                cores_per_node: 1

logical_cpus_per_core: 2

threads_per_core: 1
pool_dir: "/proj/awi"

pool_directories:
        pool: "/proj/awi/"
        projects: "/proj/awi/"


submitted: false
hyper_flag: ""

# standard environment setup
#
#

useMPI: cray_mpich

module_actions:
        - "unload craype"
        - "load craype/2.6.2"
        - "load PrgEnv-cray/6.0.4"
        - "load alps pbs"
        - "load cray-mpich/7.7.3"
        - "load craype-x86-skylake"
        - "load cmake/3.14.0"
        - "load cray-hdf5-parallel/1.10.2.0"
        - "load cray-netcdf-hdf5parallel/4.6.1.3"
        - "load fftw/2.1.5.9"
        - "load proj4/5.1.0"

export_vars:
        HDF5ROOT: $HDF5_ROOT
        NETCDFFROOT: $NETCDF_DIR
        NETCDFROOT: $NETCDF_DIR
        NETCDF_Fortran_INCLUDE_DIRECTORIES: $NETCDFROOT/include
        NETCDF_CXX_INCLUDE_DIRECTORIES: $NETCDFROOT/include
        NETCDF_CXX_LIBRARIES: $NETCDFROOT/lib
        PERL5LIB: /usr/lib64/perl5
        XML2ROOT: /usr
        ZLIBROOT: /usr
        TMPDIR: /tmp
        PMI_LABEL_ERROUT: 1
        DR_HOOK_IGNORE_SIGNALS: -1

        # enable full MPI thread support level (MPI_THREAD_MULTIPLE)
        MPICH_MAX_THREAD_SAFETY: multiple # to also switch to an alternative (probably with faster locking) multi threading implementation of the cray-mpich library, use the compiler flag -craympich-mt
        MPICH_CRAY_OPT_THREAD_SYNC: 0 # the Cray MPICH library falls back to using the pthread_mutex-based thread-synchronization implementation
        MPICH_OPT_THREAD_SYNC: 0 # seems to be a duplicate variable which also appears in some documentation instead of MPICH_CRAY_OPT_THREAD_SYNC (but this one brings a huge speed gain on aleph)

        # for the fesom cmake setup
        ENABLE_ALEPH_CRAYMPICH_WORKAROUNDS: ''
        FC: ftn
        CC: cc
        CXX: CC

further_reading:
        - batch_system/pbs.yaml
