# BLOGIN YAML CONFIGURATION FILES

name: blogin
account: None

choose_general.use_hyperthreading:
        "0":
                hyperthreading_flag: "--ntasks-per-core=1"
        "*":
                hyperthreading_flag: ""

accounting: true

"batch_system": "slurm"

jobtype: compute
sh_interpreter: "/bin/bash"

choose_jobtype:
        tidy_and_resubmit:
                partition: standard96
        post:
                partition: standard96
        compute:
                partition: standard96


choose_partition:
        standard96:
                cores_per_node: 96

logical_cpus_per_core: 2

threads_per_core: 1

pool_directories:
        pool: "/scratch/usr/hbkawi"
        focipool: "/scratch/usr/shkifmsw/foci_input2"

pool_dir:  "/scratch/usr/hbkawi"


useMPI: intelmpi

# standard environment setup
#
module_actions:
        - "purge"
        - "load slurm"
        - "load HLRNenv"
        - "load sw.skl"
        - "load cmake"
        - "load intel/19.0.5"
        - "load cdo nco"

choose_useMPI:
        intelmpi:
                add_module_actions:
                        - "unload impi"
                        - "load impi/2019.5"
                fc: mpiifort
                f77: mpiifort
                mpifc: mpiifort
                mpicc: mpiicc
                cc: mpiicc
                cxx: mpiicpc

                add_export_vars:
                        # Recommended by HLNR support when using an MPI binary and srun
                        - "SLURM_CPU_BIND=none"

                launcher_flags: "--mpi=pmi2 -l --kill-on-bad-exit=1 --cpu_bind=cores"

export_vars:
        - "LC_ALL=en_US.utf-8"

        - "FC=${fc}"
        - "F77=${f77}"
        - "MPIFC=${mpifc}"
        - "MPICC=${mpicc}"
        - "CC=${cc}"
        - "CXX=${cxx}"
        - "MPIROOT=\"$(${mpifc} -show | perl -lne 'm{ -I(.*?)/include } and print $1')\""
        - "MPI_LIB=\"$(${mpifc} -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')\""

        # Replace in the future when system provided modules and libraries are reliable
        - "IO_LIB_ROOT=/home/shkifmsw/sw/HPC_libraries/intel2019.0.5_impi2019.5_20200811"
        - "LD_LIBRARY_PATH=$IO_LIB_ROOT/lib:$LD_LIBRARY_PATH"

        - "ZLIBROOT=$IO_LIB_ROOT"
        - "SZIPROOT=$IO_LIB_ROOT"
        - "HDF5ROOT=$IO_LIB_ROOT"
        - "HDF5_ROOT=$HDF5ROOT"
        - "NETCDFROOT=$IO_LIB_ROOT"
        - "NETCDFFROOT=$IO_LIB_ROOT"
        - "HDF5_C_INCLUDE_DIRECTORIES=$HDF5_ROOT/include"
        - 'NETCDF_Fortran_INCLUDE_DIRECTORIES="$NETCDFFROOT/include"'
        - "NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include"
        - "NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include"
        # seems to be ECHAM specific, leave it here for now
        - 'OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"'

        # seb-wahl: removed as NetCDF libraries are already in the LD_LIBRARY_PATH (see above)
        #- "NETCDF_DIR=/sw/dataformats/netcdf/intel.18/4.7.3/skl/"
        #- "LD_LIBRARY_PATH=$NETCDF_DIR/lib/:$LD_LIBRARY_PATH"

further_reading:
        - batch_system/slurm.yaml
