###############################################################################
################# AWICM-1-RECOM YAML CONFIGURATION FILE #######################
###############################################################################

general:
    model: awicm_recom
    #model_dir: ${esm_master_dir}/awicm-${version}

    coupled_setup: True

    include_models:
        - echam
        - fesom
        - recom
        - oasis3mct

    version: "1.1"
    scenario: "PI-CTRL"
    resolution: ${echam.resolution}_${fesom.resolution}
    postprocessing: false
    post_time: "00:05:00"
    choose_general.resolution:
        T63_CORE2:
            compute_time: "02:00:00"
        T63_REF87K:
            compute_time: "02:00:00"
        T63_REF:
            compute_time: "02:00:00"
    available_versions:
        - '1.0'
        - '1.0-recom'
        - CMIP6
    choose_version:
        '1.0':
            couplings:
                - fesom-1.4+echam-6.3.04p1
        '1.0-recom':
            couplings:
                - fesom-1.4+recom-2.0+echam-6.3.04p1
        CMIP6:
            couplings:
                - fesom-1.4+echam-6.3.04p1


#########################################################################################
########### necessary changes to submodels compared to standalone setups ################
#########################################################################################

echam:
    restart_firstlast: "first"
    namelist_changes:
        namelist.echam:
            runctl:
                lcouple: .true.
    adj_input_dir: "${fesom.mesh_dir}/tarfiles${echam.resolution}/input/echam6"
    model_dir: ${general.model_dir}/echam-${echam.version}
    setup_dir: ${general.model_dir}
    ocean_resolution: "${fesom.resolution}"
    remove_forcing_files:
        - sst
        - sic
    version: "6.3.04p1"

# kh 20.03.20 values may be superseded by section choose_computer.cores_per_node: in .../configs/echam/echam.yaml
    choose_general.resolution:
        T63_CORE2:
            nproca: 24
            nprocb: 18
        T63_REF87K:
            nproca: 24
            nprocb: 18
        T63_REF:
            nproca: 24
            nprocb: 18


#########################################################################################


jsbach:
    adj_input_dir: "${fesom.mesh_dir}/tarfiles${echam.resolution}/input/jsbach"
    choose_jsbach.dataset:
        "r0009":
            cover_fract_dir: "${fesom.mesh_dir}/tarfiles${echam.resolution}/input/jsbach"
        "r0008":        
            cover_fract_dir: "${fesom.mesh_dir}/tarfiles${echam.resolution}/input/jsbach"
    namelist_changes:
        namelist.jsbach:
            hydrology_ctl:
                gethd: "remove_from_namelist"
                puthd: "remove_from_namelist"
    version: "3.20"

    choose_computer.name:
        ollie:
            dynveg_file_ending: ""
            no_dynveg_file_ending: ""

#########################################################################################


fesom:
    choose_general.version:
        "1.1":
            version: "1.4"
        "CMIP6":
            version: "1.4"
        "2.0":
            version: "2.0"
    choose_general.resolution:
        T63_CORE2:
            nproc: 288
        T63_REF87K:
            nproc: 216
        T63_REF:
            nproc: 128

    opbnd_dir: ""
    tide_forcing_dir: ""
    forcing_data_dir: ""
    model_dir: ${general.model_dir}/fesom-${fesom.version}
    setup_dir: ${general.model_dir}

    add_namelist_changes:
        namelist.oce:
            boundary:
                restore_s_surf: 0.0

    leapyear: True
    asforcing: ECHAM5

    # env variable `AWI_FESOM_YAML` is used by fesom/fesom_cpl/output_scheduler and
    # its value can be checked in finished_config.yaml:
    runtime_environment_changes:
        add_export_vars:
            AWI_FESOM_YAML:
                output_schedules:
                    # fesom part (defaults defined in fesom.yaml):
                    -
                        vars: [restart]
                        unit: ${fesom.restart_unit}
                        first: ${fesom.restart_first}
                        rate: ${fesom.restart_rate}
                    -
                        vars: ${fesom.yearly_outputs}
                        unit: y
                        first: ${fesom.yearly_outputs_start}
                        rate: 1
                    -
                        vars: ${fesom.monthly_outputs}
                        unit: m
                        rate: 1
                    -
                        vars: ${fesom.daily_outputs}
                        unit: d
                        rate: 1
                    -
                        vars: ${fesom.12_step_outputs}
                        unit: s
                        rate: 12
                    # recom part (defaults defined in e.g. fesom-recom.yaml or awicm_recom.yaml):
                    -
                        vars: ${recom.yearly_outputs}
                        unit: y
                        first: ${fesom.yearly_outputs_start}
                        rate: 1
                    -
                        vars: ${recom.monthly_outputs}
                        unit: m
                        rate: 1
                    -
                        vars: ${recom.daily_outputs}
                        unit: d
                        rate: 1
                    -
                        vars: ${recom.12_step_outputs}
                        unit: s
                        rate: 12


#########################################################################################

recom:
    # NOTE: look at README.md for description of the namelists
    namelist_dir: "${esm_namelist_dir}/${model}/awicm_recom/"

    # namelist.recom and associated output for coupled setup (fesom+recom+echam):
    # --> bgc_num = 22, diags3d_num = 2
    config_sources:
        recom: "${namelist_dir}/namelist.recom_co2_coupling"
    add_config_in_work:
        recom: "namelist.recom"
    yearly_outputs: []
    monthly_outputs: [aCO2,aFe,age01,alphaCO2,aN,benC,benCalc,benN,benSi,bgc01,bgc02,bgc03,bgc04,bgc05,bgc06,bgc07,bgc08,bgc09,bgc10,bgc11,bgc12,bgc13,bgc14,bgc15,bgc16,bgc17,bgc18,bgc19,bgc20,bgc21,bgc22,CO2f,CO2y,denb,diags3d01,diags3d02,dpCO2s,GNAd,GNAn,GPPd,GPPn,Hp,Kw,NNAd,NNAn,NPPd,NPPn,O2f,PAR,pCO2s,rDIN,rDOC,rDON,rDSi,slp,virtual_alk,virtual_dfe,virtual_dic,virtual_din,virtual_dsi,virtual_oxy,w10w]
    daily_outputs: []
    12_step_outputs: []

#########################################################################################

oasis3mct:
    model_dir: ${general.model_dir}/oasis

    process_ordering:
        - fesom
        - echam

    a2o_lag: "${echam.time_step}"
    o2a_lag: "${fesom.time_step}"
    a2o_seq: 2

    coupling_time_step: 3600
    coupling_target_fields:
        o2a_flux:
            - 'sst_atmo:sit_atmo:sie_atmo <--distwgt-- sst_feom:sit_feom:sie_feom'
            - 'snt_atmo <--distwgt-- snt_feom'
            - 'co2_atmo <--distwgt-- co2_feom'

        a2o_flux:
            - 'taux_oce:tauy_oce:taux_ico:tauy_ico <--bicubic-- taux_atm:tauy_atm:taux_ica:tauy_ica'
            - 'prec_oce <--distwgt-- prec_atm'
            - 'snow_oce <--distwgt-- snow_atm'
            - 'evap_oce <--distwgt-- evap_atm'
            - 'subl_oce <--distwgt-- subl_atm'
            - 'heat_oce <--distwgt-- heat_atm'
            - 'heat_ico <--distwgt-- heat_ica'
            - 'heat_swo <--distwgt-- heat_swa'
            - 'hydr_oce <--distwgt-- hydr_atm'
            - 'co2c_oce <--distwgt-- co2c_atm'
            - 'w10w_oce <--distwgt-- w10w_atm'

    coupling_directions:
        'feom->atmo':
            lag: ${o2a_lag}
            seq: 2
        'atmo->feom':
            lag: ${a2o_lag}
            seq: ${a2o_seq}

    coupling_methods:
        distwgt:
            time_transformation: instant
            remapping:
                distwgt:
                    search_bin: latitude
                    nb_of_search_bins: 15
                    nb_of_neighbours: 6
        bicubic:
            time_transformation: instant
            remapping:
                bicubic:
                    search_bin: latitude
                    nb_of_search_bins: 15

    add_restart_out_files:
        rmp_a2f_B: rmp_a2f_B
        rmp_a2f_D: rmp_a2f_D
        rmp_f2a_D: rmp_f2a_D

    add_restart_out_in_work:
        rmp_a2f_B: rmp_atmo_to_feom_BICUBIC.nc
        rmp_a2f_D: rmp_atmo_to_feom_DISTWGT.nc
        rmp_f2a_D: rmp_feom_to_atmo_DISTWGT.nc

    add_restart_out_sources:
        rmp_a2f_B: rmp_atmo_to_feom_BICUBIC.nc
        rmp_a2f_D: rmp_atmo_to_feom_DISTWGT.nc
        rmp_f2a_D: rmp_feom_to_atmo_DISTWGT.nc

    add_restart_in_files:
        rmp_a2f_B: rmp_a2f_B
        rmp_a2f_D: rmp_a2f_D
        rmp_f2a_D: rmp_f2a_D

    add_restart_in_in_work:
        rmp_a2f_B: rmp_atmo_to_feom_BICUBIC.nc
        rmp_a2f_D: rmp_atmo_to_feom_DISTWGT.nc
        rmp_f2a_D: rmp_feom_to_atmo_DISTWGT.nc

    add_restart_in_sources:
        rmp_a2f_B: rmp_atmo_to_feom_BICUBIC.nc
        rmp_a2f_D: rmp_atmo_to_feom_DISTWGT.nc
        rmp_f2a_D: rmp_feom_to_atmo_DISTWGT.nc


