# SLURM YAML CONFIGURATION FILE
#
#

header_start: "#SBATCH"
submit: sbatch
launcher: srun
mail_type: NONE
account: None



# intermediate vars

mail1: ""
mail2: ""

exclusive_flag: "--exclusive"

choose_accounting:
        True:
                accounting_flag: "--account=${general.account}"

choose_mail_type:
        "*":
                mail1:  "--mail_type=${mail_type}"
choose_mail_user:
        "*":
                mail2:  "--mail_user=${mail_user}"

notification_flag: "${mail1} ${mail2}"
single_proc_submit_flag: "--ntasks-per-node=1"
tasks_flag: "--ntasks=@tasks@"
partition_flag: "--partition=${partition}"
time_flag: "--time=${compute_time}"
additional_flags: ""
output_flags: "--output=${expid}_${jobtype}_${general.current_date!syear!smonth!sday}-${general.end_date!syear!smonth!sday}_%j.log --error=${expid}_${jobtype}_${general.current_date!syear!smonth!sday}-${general.end_date!syear!smonth!sday}_%j.log"
name_flag: "--job-name=${expid}"

choose_launcher:
        srun:
                launcher_flags: "-l --kill-on-bad-exit=1 --cpu_bind=cores"
        mpiexec.hydra:
                launcher_flags: "-bootstrap slurm"
        mpirun:
                launcher_flags: "-l"

submitted: false
script_name: "<--methods.scriptname--"
actual_script_dir: "<--methods.script_dir--"
hostname_list: "DUMMY_HOST1 DUMMY_HOST2"

choose_SLURM_NNODES:
        "*":
                submitted: true
                script_name: "<--scriptname--"
                actual_script_dir: "<--script_dir--"
                total_nnodes: ${SLURM_NNODES}
                hostname_list: "<--show_hostnames--"

                #"<--scriptname--":
                #method: "squeue --job ${JOB_ID} -o '%o' | cut -f1 -d' ' | basename | cut -f1 -d' '"
                #"<--scriptdir--":
                #method: "squeue --job ${JOB_ID} --format '%Z' squeue --job ${JOB_ID} --format '%Z'"
                #"<--show_hostnames--":
                #method: "scontrol show hostnames"

config_files:
        hostfile: hostfile_srun

        #config_create:
        #hostfile:
        #        - "[[setup.orderedexecs-->MODEL]]<--startproc-- - MODEL<--endproc-- ./MODEL<--exe-- <--append--"

execution_command: "${launcher} ${launcher_flags} --multi-prog ${config_files.hostfile}"

check_error:
        "srun: error:" :
                frequency: 30
                method: "kill"
                message: "SLURM ERROR: slurm endet with an error, exiting."
                file: "stdout"

        "slurmstepd: error: execve():" :
                frequency: 600
                method: "kill"
                message: "SLURM ERROR: slurm probably didn't find executable"
                file: "stdout"
