#########################################################################################
######################### FESOM-RECOM YAML CONFIGURATION FILE ###########################
#########################################################################################

general:
        model: fesom-recom
        #model_dir: ${esm_master_dir}/fesom-recom-${version}

        version: "1.4"

        coupled_setup: False
        standalone: True

        include_models:
                - recom
                - fesom

        available_versions:
        - '1.4'
        - '2.0'
        choose_version:
          '1.4':
            couplings:
            - fesom-1.4+recom-2.0

        choose_computer.name:
                blogin:
                        add_runtime_environment_changes:
                                add_add_export_vars:
                                        # MA: Delete in the future, when libraries in blogin.yaml
                                        # do the job for fesom-recom-1.4 as well (talk about this
                                        # with Sebastian)
                                        - "IO_LIB_ROOT=/sw/dataformats/netcdf/intel.18/4.7.3/skl/"
                                        - "LD_LIBRARY_PATH=$IO_LIB_ROOT/lib:$LD_LIBRARY_PATH"
                                        - "ZLIBROOT=$IO_LIB_ROOT"
                                        - "SZIPROOT=$IO_LIB_ROOT"
                                        - "HDF5ROOT=$IO_LIB_ROOT"
                                        - "HDF5_ROOT=$HDF5ROOT"
                                        - "NETCDFROOT=$IO_LIB_ROOT"
                                        - "NETCDFFROOT=$IO_LIB_ROOT"
                                        - "HDF5_C_INCLUDE_DIRECTORIES=$HDF5_ROOT/include"
                                        - "NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include"
                                        - "NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/netcdf-cxx4-4.3.1/cxx4/"
                                        - 'OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"'


#########################################################################################
########### necessary changes to submodels compared to standalone setups ################
#########################################################################################

fesom:
        version: "1.4-recom-mocsy-slp"
        model_dir: "${general.model_dir}/fesom-${fesom.version}/"
        setup_dir: "${general.model_dir}"

        time_step: 900
        output_unit: "${restart_unit}"
        leapyear: false

        opbnd_dir: ""
        tide_forcing_dir: ""

        asforcing: CORE2
        asforcing_wind_rad_precip: JRA55


        namelist_changes:   # Change to add_namelist_changes when the bug is fixed
                namelist.config:
                        inout:
                                levelwise_output: true
                                output_length_unit: "${output_unit}"
                                output_length_unit_restart: "${restart_unit}"
                        #mesh_def:
                                #part_format: 0  #this option is required because of two ways
                                                #of storring mapping arrays are currently in use
                                                #option with part_format=0 shall be used in future!
                namelist.diag:
                        diag_flag:
                                diag_oce_KE: "remove_from_namelist"
                                diag_oce_energy_conv: "remove_from_namelist"
                                diag_oce_Kv: "remove_from_namelist"
                                diag_mesh: "remove_from_namelist"
                namelist.forcing:
                        forcing_exchange_coeff:
                                Cd_atm_ice: 1.3e-3
                        forcing_source:
                                wind_data_source: "${asforcing_wind_rad_precip}"
                                rad_data_source: "${asforcing_wind_rad_precip}"
                                precip_data_source: "${asforcing_wind_rad_precip}"
                                wind_ttp_ind: 5
                                rad_ttp_ind: 5
                                precip_ttp_ind: 5
                                runoff_ttp_ind: 3
                        forcing_reso:
                                forcing_grid: 'T319'    #'T62','T319', 'other'
                                forcing_dx: 0.4         #degree; from here required for 'other'
                                forcing_dy: 0.4
                                forcing_ni: 900         #number of grid points
                                forcing_nj: 451
                        forcing_bulk:
                                AOMIP_drag_coeff: true
                namelist.ice:
                        ice_stress:
                                Pstar: 27500.0          #23000. 27500. 30000.
                                c_pressure: 15.0        #20.0
                        ice_fric:
                                Cd_oce_ice: 1.0e-2      #5.5e-3  3.0e-3  !Qiang ab 1964
                        ice_rheology:
                                evp_rheol_steps: 300
                        ice_scheme:
                                ice_gamma_fct: 0.05
                        ice_therm:
                                Sice: 5.0
                                h0: 0.6
                namelist.oce:
                        viscdiff:
                                Kh0: 800.0
                                brine_rejection_param: false
                        oce_scheme:
                                gamma_fct: 0.4
                        age_tracer:
                                use_age_tracer: true
                                age_tracer_start_year: "${age_tracer_sy}"
                        tracer_cutoff:
                                limit_salinity: false
                                salinity_min: 5.0

        # env variable `AWI_FESOM_YAML` is used by fesom/fesom_cpl/output_scheduler and
        # its value can be checked in finished_config.yaml:
        runtime_environment_changes:
                add_export_vars:
                        AWI_FESOM_YAML:
                                output_schedules:
                                        # fesom part (defaults defined in fesom.yaml):
                                        -
                                                vars: [restart]
                                                unit: ${fesom.restart_unit}
                                                first: ${fesom.restart_first}
                                                rate: ${fesom.restart_rate}
                                        -
                                                vars: ${fesom.yearly_outputs}
                                                unit: y
                                                first: ${fesom.yearly_outputs_start}
                                                rate: 1
                                        -
                                                vars: ${fesom.monthly_outputs}
                                                unit: m
                                                rate: 1
                                        -
                                                vars: ${fesom.daily_outputs}
                                                unit: d
                                                rate: 1
                                        -
                                                vars: ${fesom.12_step_outputs}
                                                unit: s
                                                rate: 12
                                        # recom part (defaults defined in e.g. fesom-recom.yaml or awicm_recom.yaml):
                                        -
                                                vars: ${recom.yearly_outputs}
                                                unit: y
                                                first: ${fesom.yearly_outputs_start}
                                                rate: 1
                                        -
                                                vars: ${recom.monthly_outputs}
                                                unit: m
                                                rate: 1
                                        -
                                                vars: ${recom.daily_outputs}
                                                unit: d
                                                rate: 1
                                        -
                                                vars: ${recom.12_step_outputs}
                                                unit: s
                                                rate: 12

        choose_lresume:
                true:
                        choose_general.run_number:
                                1:      # Restart from runscript
                                        age_tracer_sy: "${first_initial_year}"
                                        first_initial_year: "${general.first_initial_year}"
                                        ini_parent_exp_id: "${general.ini_parent_exp_id}"
                                        ini_restart_dir: "${general.ini_restart_dir}/fesom/"
                                        ini_parent_date: "${prev_date}"

                                "*":
                                        age_tracer_sy: "${general.initial_date!syear}"
                false:
                        age_tracer_sy: "${general.initial_date!syear}"


#########################################################################################

recom:
        version: "2.0"
        model_dir: "${general.model_dir}/recom/"
        setup_dir: "${general.model_dir}"

        time_step: "${fesom.time_step}"

        choose_lresume:
                true:
                        choose_general.run_number:
                                1:      # Restart from runscript
                                        ini_parent_exp_id: "${general.ini_parent_exp_id}"
                                        ini_restart_dir: "${general.ini_restart_dir}/recom/"
                                        ini_parent_date: "${prev_date}"

        # namelist.recom and associated output for offline setup (fesom+recom):
        # --> bgc_num = 28, diags3d_num = 20
        config_sources:
                recom: "${namelist_dir}/namelist.recom"
        add_config_in_work:
                recom: "namelist.recom"
        yearly_outputs: []
        monthly_outputs: [aCO2,aFe,age01,alphaCO2,aN,benC,benCalc,benN,benSi,bgc01,bgc02,bgc03,bgc04,bgc05,bgc06,bgc07,bgc08,bgc09,bgc10,bgc11,bgc12,bgc13,bgc14,bgc15,bgc16,bgc17,bgc18,bgc19,bgc20,bgc21,bgc22,bgc23,bgc24,bgc25,bgc26,bgc27,bgc28,CO2f,CO2y,denb,diags3d01,diags3d02,diags3d03,diags3d04,diags3d05,diags3d06,diags3d07,diags3d08,diags3d09,diags3d10,diags3d11,diags3d12,diags3d13,diags3d14,diags3d15,diags3d16,diags3d17,diags3d18,diags3d19,diags3d20,dpCO2s,GNAd,GNAn,GPPd,GPPn,Hp,Kw,NNAd,NNAn,NPPd,NPPn,O2f,PAR,pCO2s,rDIN,rDOC,rDON,rDSi,slp,virtual_alk,virtual_dfe,virtual_dic,virtual_din,virtual_dsi,virtual_oxy,w10w]
        daily_outputs: []
        12_step_outputs: []

