# Miguel:
# OCECTL contains modifications to the ``iolist`` array, where this modifications occur
# for specific terms of the array through the syntax ``iolist(<term_id>) =
# <a_given_array>``. Unfortunatelly the ``f90nml`` module is unable to parse this 
# syntax correctly. Therefore, I have removed member from the namelist and added here
# inside ``add_namelist_changes``. This produces the correct final namelists.
# Same occurs for NAMELIST_BGC

choose_version:
        "1.6.3p2":
                add_namelist_changes:
                        OCECTL:
                                ioctl:
                                        iolist(100): [99, 'rerun_mpiesm_PI_ctrl_ham_mpiom.nc', 'nc2', 1, 2, 3, 4, 5, 7, 9,
                                                      10, 13, 15, 35, 36, 39, 82, 99, 110, 111, 141, 501, 502, 503,
                                                      504]
                                        iolist(99): [2, 'mpiesm_PI_ctrl_ham_mpiom_data_2d_mm.nc', 'nc2', 1, 11, 12, 13, 14,
                                                     15, 16, 17, 19, 20, 27, 35, 36, 66, 70, 78, 79, 104, 109, 123,
                                                     124, 125, 126, 127, 128, 134, 136, 138, 139, 140, 141, 149,
                                                     150, 151, 153, 165, 168, 169, 170, 181, 183, 215, 216, 217,
                                                     218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229,
                                                     275, 276, 277, 278, 285, 286, 287, 288, 548, 549, 521, 1013,
                                                     1015, 1016, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025,
                                                     1026, 1027, 1028, 1036, 1037, 1038, 1039, 1040, 1041, 1042,
                                                     1043, 1044, 1045, 1046, 1047, 1048]
                                        iolist(98): [2, 'mpiesm_PI_ctrl_ham_mpiom_timeser_mm.nc', 'nc2', 508, 509, 520, 513,
                                                     514, 515, 516, 517, 518, 519, 592, 644, 645, 724, 725, 684,
                                                     685, 809, 613, 614, 615, 623, 624, 625, 633, 634, 635, 703,
                                                     704, 705, 612, 622, 632, 642, 652, 662, 672, 682, 692, 702,
                                                     712, 722, 732, 742, 752, 762, 770, 771, 772, 774, 775, 780,
                                                     781, 782, 784, 785, 790, 791, 792, 794, 795, 800, 801, 802,
                                                     804, 805, 810, 811, 812, 814, 815, 820, 821, 822, 823, 824,
                                                     825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836,
                                                     837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848,
                                                     849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860,
                                                     861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872,
                                                     873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884,
                                                     885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
                                                     897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908,
                                                     909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920,
                                                     921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932,
                                                     933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944,
                                                     945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956,
                                                     957, 958, 959, 960, 961, 962, 963, 1001, 1050, 1051, 1052,
                                                     1053, 1054, 1055]
                                        iolist(97): [2, 'mpiesm_PI_ctrl_ham_mpiom_data_moc_mm.nc', 'nc2', 93, 94, 95, 96, 97,
                                                     98, 100, 101, 102, 106, 107, 108, 1093, 1094, 1095, 1096, 1097,
                                                     1098, 1099, 1100, 1101, 1112, 1113, 1114]
                                        iolist(96): [3, 'mpiesm_PI_ctrl_ham_mpiom_monitoring_ym.nc', 'nc2', 515, 516, 518,
                                                     519, 520, 622, 652, 672, 703, 800, 836, 837, 900, 901, 936,
                                                     950, 951, 952, 953, 955, 956, 958, 959, 961, 962, 1001]
                                        iolist(95): [2, 'mpiesm_PI_ctrl_ham_mpiom_data_3d_mm.nc', 'nc2', 2, 3, 4, 5, 6, 7,
                                                     18, 21, 22, 23, 24, 39, 54, 110, 111, 112, 135, 152, 197, 214,
                                                     279]
                                        iolist(94): [6402, 'mpiesm_PI_ctrl_ham_mpiom_data_2d_mmin.nc', 'nc2', 276]
                                        iolist(93): [12802, 'mpiesm_PI_ctrl_ham_mpiom_data_2d_mmax.nc', 'nc2', 276]
                                        iolist(92): [12801, 'mpiesm_PI_ctrl_ham_mpiom_data_2d_dmax.nc', 'nc2', 276]
                                        iolist(91): [3, 'mpiesm_PI_ctrl_ham_mpiom_data_2d_ym.nc', 'nc2', 277, 278]
                                        iolist(80): [107, 'mpiesm_PI_ctrl_ham_mpiom_data_2d_3h.nc', 'nc2', 12]
                                        iolist(90): [1, 'mpiesm_PI_ctrl_ham_mpiom_data_2d_dm.nc', 'nc2', 12, 13, 14, 15, 16,
                                                     104, 109, 140, 141, 276, 1016, 1022, 1023, 1024, 1025, 1026]
                                        iolist(87): [3, 'mpiesm_PI_ctrl_ham_mpiom_data_3d_ym.nc', 'nc2', 25, 26, 28, 30, 88,
                                                     90, 111, 152, 282, 1029, 1030, 1031, 1032]
                                        iolist(89): [90, 'mpiesm_PI_ctrl_ham_mpiom_map.nc', 'nc2', 511, 1594, 1595, 1604,
                                                     1605, 1614, 1615, 1624, 1625, 1634, 1635, 1644, 1645, 1654,
                                                     1655, 1664, 1665, 1674, 1675, 1684, 1685, 1694, 1695, 1704,
                                                     1705, 1714, 1715, 1724, 1725, 1734, 1735, 1744, 1745, 1754,
                                                     1755, 1764, 1765, 1774, 1775, 1784, 1785, 1794, 1795, 1804,
                                                     1805, 1814, 1815]
                                        iolist(88): [90, 'mpiesm_PI_ctrl_ham_mpiom_fx.nc', 'nc2', 56, 57, 84, 85, 86, 87,
                                                     154, 155, 172, 174, 175, 184, 185, 186, 187, 188, 189, 190,
                                                     191, 192, 193, 194, 195, 196, 197]
                        NAMELIST_BGC:
                                ioctl:
                                        iolist(100): [99, 'rerun_mpiesm_PI_ctrl_ham_hamocc.nc', 'nc2', 7, 10, 11, 12, 13, 14,
                                                      15, 16, 17, 20, 21, 22, 23, 24, 27, 28, 29, 30, 31, 36, 37,
                                                      38, 41, 44, 45, 46, 47, 48, 49, 50, 51, 54, 55, 56, 57, 58,
                                                      59, 60, 61, 62, 63, 64, 203, 204, 205, 145]
                                        iolist(99): [4002, 'dust_deposition.nc', 'nc2', 34]
                                        iolist(98): [4002, 'nitrogen_deposition.nc', 'nc2', 35]
                                        iolist(97): [3, 'mpiesm_PI_ctrl_ham_hamocc_data_3d_ym.nc', 'nc2', 36, 704, 731, 764,
                                                     787, 781, 739, 762, 783, 782, 747, 752, 701, 745, 20, 700, 765,
                                                     22, 754, 712, 724, 709, 766, 743, 719, 28, 707, 750, 735, 770,
                                                     789, 142, 727, 729, 166, 769, 741, 771, 772, 758, 773, 774,
                                                     775, 776, 777, 778, 779, 780, 784, 711, 785, 786, 788, 141,
                                                     100]
                                        iolist(96): [2, 'mpiesm_PI_ctrl_ham_hamocc_data_3d_mm.nc', 'nc2', 69, 70, 71, 84, 85,
                                                     86, 100, 711, 141, 143, 292, 293, 294, 295, 296, 143, 510, 700,
                                                     701, 704, 707, 709, 712, 719, 724, 727, 729, 731, 735, 736,
                                                     739, 741, 743, 745, 147, 747, 750, 751, 752, 754, 758, 759,
                                                     762, 764, 765, 766, 236, 780, 778, 598, 599, 600, 601, 602,
                                                     603, 604, 605, 606, 607, 776, 785, 772, 782, 187, 188, 774,
                                                     788]
                                        iolist(95): [2, 'mpiesm_PI_ctrl_ham_hamocc_data_2d_mm.nc', 'nc2', 61, 62, 64, 93,
                                                     755, 721, 742, 737, 733, 723, 716, 93, 738, 763, 107, 110, 111,
                                                     112, 114, 115, 116, 117, 120, 122, 123, 124, 127, 129, 131,
                                                     137, 157, 159, 714, 715, 749, 710, 746, 708, 730, 705, 791,
                                                     207, 210, 211, 214, 215, 703, 174, 201, 713, 206, 717, 718,
                                                     720, 722, 725, 726, 728, 732, 734, 740, 744, 748, 753, 756,
                                                     757, 760, 207, 761, 215, 790, 792, 608, 609, 417, 413, 419,
                                                     767, 796, 768, 797, 798, 799, 706, 94, 121, 144, 160, 174, 185,
                                                     186]
                                        iolist(94): [1, 'mpiesm_PI_ctrl_ham_hamocc_data_2d_dm.nc', 'nc2', 767, 768]
                                        iolist(93): [101, 'mpiesm_PI_ctrl_ham_hamocc_co2.nc', 'nc2', 301, 303, 304, 305, 306,
                                                     307, 308, 309, 310, 311, 312, 313, 314, 203, 204, 205]
                                        iolist(92): [3, 'mpiesm_PI_ctrl_ham_hamocc_monitoring_ym.nc', 'nc2', 500, 501, 502,
                                                     503, 504, 505, 506, 507, 508, 509, 517, 519, 520, 523, 529,
                                                     530, 531, 532, 533, 534, 535]
                                        iolist(91): [3, 'mpiesm_PI_ctrl_ham_hamocc_data_sedi_ym.nc', 'nc2', 38, 41, 44, 45,
                                                     46, 47, 48, 49, 50, 51, 54, 55, 56, 57, 58, 59, 60, 63, 94, 95,
                                                     96, 97, 167, 168, 280, 281, 282, 283, 284, 285, 286, 287]
