# MPIOM YAML CONFIGURATION FILE
#

model: mpiom
type: ocean

available_versions:
- 1.6.2p3
- 1.6.3
- 1.6.3p2
choose_version:
  1.6.2p3:
    branch: 1.6.2p3
  1.6.3:
    branch: 1.6.3
  1.6.3p2:
    branch: 1.6.3p2
install_bins: bin/mpiom.x
clean_command: make clean
comp_command: make -j `nproc --all`
conf_command: ./configure --prefix=${model_dir} --disable-mh-file --enable-HAMOCC --with-mpi=intelmpi
git-repository: https://gitlab.dkrz.de/modular_esm/mpiom.git

metadata:
        Institute: MPI-Met
        Description:
                The ocean-sea ice component of the MPI-ESM. MPIOM is a primitive equation
                model (C-Grid, z-coordinates, free surface) with the hydrostatic and
                Boussinesq assumptions made.
        Authors: Till Maier-Reimer, Helmuth Haak, Johann Jungclaus
        Publications:
                - "Characteristics of the ocean simulations in the Max Planck Institute Ocean Model (MPIOM) the ocean component of the MPI-Earth system model <https://doi.org/10.1002/jame.20023>"
                - "The Max-Planck-Institute global ocean/sea ice model with orthogonal curvilinear coordinates <https://doi.org/10.1016/S1463-5003(02)00015-X>"
        License:
                Please make sure you have a licence to use MPIOM. In case you are unsure,
                please contact redmine...

executable: mpiom
version: 1.6.3

standalone_model: True

setup_dir: "${model_dir}"
bin_dir: "${setup_dir}/bin"
namelist_dir: "${general.esm_namelist_dir}/mpiom/${version}"

namelists:
        - "OCECTL"
        - "NAMELIST_BGC"

namelist_changes:
        OCECTL:
                ocectl:
                        dt: "${time_step}"

time_step: 2700
resolution: GR15

choose_resolution:
        GR15:
                nx: 120
                ny: 101
        GR30:
                nx: 254 # 256 @CHRISTIAN: should it be 254 or 256? inconsistencies
                            # between old runscripts MPIOM presets and OASIS namcouple
                ny: 220

coupling_fields:
        SSTOCEAN:
                grid: oces
        SITOCEAN:
                grid: oces
        SICOCEAN:
                grid: oces
        SNTOCEAN:
                grid: oces
        OCUOCEAN:
                grid: oces
        OCVOCEAN:
                grid: oces
        CO2TRAOC:
                grid: oces
        CO2OCEAN:
                grid: oces
        FRIOCEAN:
                grid: oces
        FRWOCEAN:
                grid: oces
        TXWOCEAS:
                grid: oces
        TYWOCEAS:
                grid: oces
        TXIOCEAS:
                grid: oces
        TYIOCEAS:
                grid: oces
        RHIOCEAN:
                grid: oces
        CHIOCEAN:
                grid: oces
        NHWOCEAN:
                grid: oces
        SHWOCEAN:
                grid: oces
        WSVOCEAN:
                grid: oces
        CO2CONOC:
                grid: oces
        CO2FLXOC:
                grid: oces

grids:
        oces:
                name: oces
                nx: "${nx}"
                ny: "${ny}"
                oasis_grid_type: "LR"
                number_of_overlapping_points: 0 # oasis P-value

bin_files:
        mpiom_bin: "mpiom_bin"
bin_sources:
        mpiom_bin: "${bin_dir}/mpiom.x"
bin_in_work:
        mpiom_bin: "mpiom.x"

config_sources:
        OCECTL: "${namelist_dir}/OCECTL"
        NAMELIST_BGC: "${namelist_dir}/NAMELIST_BGC"

further_reading:
        - mpiom/mpiom.compiletime_env_changes.yaml

