# MPIOM YAML CONFIGURATION FILE
#

model: mpiom
branch: 1.6.3p2
version: "1.6.3p2"

available_versions:
- 1.6.3p2
- 1.6.3p2-coupled

choose_version:
  1.6.3p2:
    branch: 1.6.3p2
  1.6.3p2-coupled:
    branch: 1.6.3p2
    conf_command: ./configure --prefix=${model_dir} --disable-mh-file --with-coupler=oasis3-mct
      --enable-HAMOCC

clean_command: make clean
comp_command: make
conf_command: ./configure --prefix=${model_dir} --disable-mh-file --enable-HAMOCC
git-repository: https://gitlab.dkrz.de/modular_esm/mpiom.git
install_bins: bin/mpiom.x

comp_executable: mpiom.x
executable: mpiom

setup_dir: "${model_dir}"
bin_dir: "${setup_dir}/bin"
