#########################################################################################
######################### MPIESM 1 YAML CONFIGURATION FILE ##############################
#########################################################################################

model: mpiesm
version: "1.2.01"
