#########################################################################################
######################### MPIESM YAML CONFIGURATION FILE ################################
#########################################################################################

general:
        model: mpiesm
        #model_dir: ${esm_master_dir}/mpiesm-${version}
        pool_dir: ${computer.pool_directories.pool}

        coupled_setup: True

        include_models:
                - echam
                - mpiom
                - oasis3mct

        version: "1.2"
        resolution: ${echam.resolution}_${mpiom.resolution}
        post_time: "00:60:00"
        choose_general.resolution:
                T31_GR30:
                        compute_time: "00:60:00"
                T63_GR15:
                        compute_time: "00:60:00"

        postprocessing: -1 #V19?, what does it mean -1?

        #choose_lresume:
        #        true:
        #                echam:
        #                        pseudo_resume_date: $(( ${echam.start_date} - ${echam.time_step}))
        #                        pseudo_end_date: $(( ${echam.next_date} - ${echam.time_step}))

        #forcing_sources:
        #        lctlib: "${model_dir}/util/running/adjunct_files/jsbach/lctlib_nlct21.def"

        available_versions:
        - 1.2.00p4
        - 1.2.01
        - 1.2.01p1
        choose_version:
          1.2.00p4:
            couplings:
            - mpiom-1.6.2p3+echam-6.3.02p4
          1.2.01:
            couplings:
            - mpiom-1.6.3+echam-6.3.04p1
          1.2.01p1:
            couplings:
            - mpiom-1.6.3p2+echam-6.3.05p2


#########################################################################################

echam:
        # namelist.echam in the run folder is almost identical to those from MPI
        # scripts. The differences are:
        # - ``nprocar`` and ``nprocbr`` are defined in ESM-Tools version (taken
        #   from the old ksh scripts)
        # - default_output = .true. (.false. for MPI)

        namelist_dir: "${general.esm_namelist_dir}/echam/${version}-mpiesm"

        namelist_changes:
                namelist.echam:
                        runctl:
                                lcouple: .true.

        choose_computer.cores_per_node:
                24:
                        choose_general.resolution:
                                T31_GR30:
                                        nnodes: 18
                                        nproca: 24
                                        nprocb: 18
                                T63_GR15:
                                        nnodes: 24
                                        nproca: 24
                                        nprocb: 24
                36:
                        choose_general.resolution:
                                T31_GR30:
                                        nnodes: 12
                                        nproca: 24
                                        nprocb: 18
                                T63_GR15:
                                        nnodes: 12
                                        nproca: 18
                                        nprocb: 20

        choose_general.version:
                CMIP6:
                    version: "6.3.04p1"
                "1.2.01p1":
                    version: "6.3.05p2"
                "1.2.01":
                    version: "6.3.04p1"
                "1.2.00":
                    version: "6.3.02p4"


#########################################################################################

jsbach:
        namelist_dir: "${general.esm_namelist_dir}/jsbach/${version}-mpiesm"

        choose_general.version:
                CMIP6:
                    version: "3.20"
                "1.2.01p1":
                    version: "3.20p1"
                "1.2.01":
                    version: "3.20"
                "1.2.00":
                    version: "3.10"


#########################################################################################

mpiom:
        resolution: GR30
        conf_command: ./configure --prefix=${model_dir} --disable-mh-file --with-coupler=oasis3-mct
          --enable-HAMOCC --with-mpi=intelmpi

        time_step: 2700
        choose_computer.cores_per_node:
                24:
                        choose_general.resolution:
                                T31_GR30:
                                        nnodes: 9
                                        nproca: 18
                                        nprocb: 12
                                T63_GR15:
                                        nnodes: 16
                                        nproca: 16
                                        nprocb: 24
                36:
                        choose_general.resolution:
                                T31_GR30:
                                        nnodes: 6
                                        nproca: 18
                                        nprocb: 12
                                T63_GR15:
                                        nnodes: 6
                                        nproca: 18
                                        nprocb: 12

        choose_general.version:
                CMIP6:
                    version: "1.6.3"
                "1.2.01p1":
                    version: "1.6.3p2"
                "1.2.01":
                    version: "1.6.3"
                "1.2.00":
                    version: "1.6.2p3"


#########################################################################################

oasis3mct:
        # @Christian: namcouple copied from MPI namcouple. The only differences with it
        # is that the ``SEQ = 1`` in each field is missing but Oasis manual states that
        # "the SEQ namcouple setting is only diagnostic and it is not required".
        # ``nb`` values in each field are also different but Oasis manual states that
        # this parameter is "UNUSED but still required for parsing".
        # OCVATMOS-OCVOCEAN and OCUATMOS-OCUOCEAN fields are labelled as vectors in the
        # MPI version but oasis3mct does not support VECTORS anymore. The log from
        # the MPI scripts you sent me shows that it is using oasis3mct, therefore, so
        # oasis3mct might not care anymore about if that parameter is defined as
        # VECTOR or SCALAR, it considers it always as a SCALAR (in fact, the oasis
        # manual states that "the optionVECTOR, which in fact leads to a scalar
        # treatment of the field (as in the previous versions), is still accepted").

        model_dir: ${general.model_dir}/oasis
        pool_dir: ${general.pool_dir}

        process_ordering:
                - mpiom
                - echam

        lresume: True
        ini_parent_date: "19500101" # not used, but needs to be present
        ini_parent_exp_id: "an_exp_id" # not used, but needs to be present
        ini_restart_dir: "${pool_dir}"

        a2o_lag: "${echam.time_step}"
        o2a_lag: "${mpiom.time_step}"
        a2o_seq: 3
        o2a_seq: 3

        coupling_time_step: 86400
        coupling_target_fields:
                sstoce1:
                        - 'SSTATMOS <--conserv-- SSTOCEAN'
                sstoce2:
                        - 'SITATMOS <--conserv-- SITOCEAN'
                sstoce3:
                        - 'SICATMOS <--conserv-- SICOCEAN'
                sstoce4:
                        - 'SNTATMOS <--conserv-- SNTOCEAN'
                sstoce5:
                        - 'OCUATMOS <--conserv-- OCUOCEAN'
                sstoce6:
                        - 'OCVATMOS <--conserv-- OCVOCEAN'
                sstoce7:
                        - 'CO2TRAAT <--conserv-- CO2TRAOC'
                sstoce8:
                        - 'CO2ATMOS <--conserv-- CO2OCEAN'
                flxatm17:
                        - 'FRIOCEAN <--conserv2-- FRIATMOS'
                flxatm18:
                        - 'FRWOCEAN <--conserv2-- FRWATMOS'
                flxatm9:
                        - 'TXWOCEAS <--bicubic-- TXWATMOU'
                flxatm11:
                        - 'TYWOCEAS <--bicubic-- TYWATMOU'
                flxatm13:
                        - 'TXIOCEAS <--bicubic-- TXIATMOU'
                flxatm15:
                        - 'TYIOCEAS <--bicubic-- TYIATMOU'
                flxatm19:
                        - 'RHIOCEAN <--conserv3-- RHIATMOS'
                flxatm20:
                        - 'CHIOCEAN <--conserv3-- CHIATMOS'
                flxatm21:
                        - 'NHWOCEAN <--conserv3-- NHWATMOS'
                flxatm22:
                        - 'SHWOCEAN <--conserv3-- SHWATMOS'
                flxatm23:
                        - 'WSVOCEAN <--conserv3-- WSVATMOS'
                flxatm24:
                        - 'CO2CONOC <--conserv3-- CO2CONAT'
                flxatm25:
                        - 'CO2FLXOC <--conserv4-- CO2FLXAT'

        coupling_directions:
                'oces->atmo':
                        lag: ${o2a_lag}
                        seq: ${o2a_seq}
                'atmo->oces':
                        lag: ${a2o_lag}
                        seq: ${a2o_seq}
                'atmo_lr->oces':
                        lag: ${a2o_lag}
                        seq: ${a2o_seq}
                'atml->oces':
                        lag: ${a2o_lag}
                        seq: ${a2o_seq}

        coupling_methods:
                conserv:
                        time_transformation: instant
                        remapping:
                                - conserv:
                                        search_bin: latitude
                                        nb_of_search_bins: 40
                                        normalization: fracarea
                                        order: first
                                - mapping:
                                        mapname: rmp_oces_to_atmo_CONSERV_FRACAREA_${general.resolution}.nc
                                        map_regrid_on: dst
                conserv2:
                        time_transformation: instant
                        remapping:
                                - conserv:
                                        search_bin: latitude
                                        nb_of_search_bins: 40
                                        normalization: fracarea
                                        order: first
                                - mapping:
                                        mapname: rmp_atmo_to_oces_CONSERV_FRACAREA_${general.resolution}.nc
                                        map_regrid_on: src
                        postprocessing:
                                conserv:
                                        method: global
                conserv3:
                        time_transformation: instant
                        remapping:
                                - conserv:
                                        search_bin: latitude
                                        nb_of_search_bins: 40
                                        normalization: fracarea
                                        order: first
                                - mapping:
                                        mapname: rmp_atmo_to_oces_CONSERV_FRACAREA_${general.resolution}.nc
                                        map_regrid_on: src
                conserv4:
                        time_transformation: instant
                        remapping:
                                - conserv:
                                        search_bin: latitude
                                        nb_of_search_bins: 40
                                        normalization: fracarea
                                        order: first
                                - mapping:
                                        mapname: rmp_atml_to_oces_CONSERV_FRACAREA_${general.resolution}.nc
                                        map_regrid_on: dst
                        postprocessing:
                                conserv:
                                        method: global
                bicubic:
                        time_transformation: instant
                        remapping:
                                - bicubic:
                                        search_bin: latitude
                                        nb_of_search_bins: 40
                                - mapping:
                                        mapname: rmp_atmo_to_oces_BICUBIC_D_${general.resolution}.nc
                                        map_regrid_on: src
