#########################################################################################
######################### MPIESM 1 YAML CONFIGURATION FILE ##############################
#########################################################################################

model: mpiesm
version: "1.2.01"
available_versions:
- 1.2.01
choose_version:
  1.2.01:
    couplings:
    - mpiom-1.6.3+echam-6.3.04p1
