#########################################################################################
######################### MPIESM 1 YAML CONFIGURATION FILE ##############################
#########################################################################################

model: mpiesm
version: "1.2.01p1"
available_versions:
- 1.2.01p1
choose_version:
  1.2.01p1:
    couplings:
    - mpiom-1.6.3p2+echam-6.3.05p2
