# PG: BUG!! This doesn't work, but should. It is overriden by the other
# add_export_vars???
#add_export_vars:
    # NOTE(PG): The version of HDF5_ROOT **WITH** an underscore is used by PISM Cmake:
    #    - "HDF5_ROOT=$HDF5ROOT"

choose_computer.name:
    ollie:
        environment_changes:
            add_module_actions:
                - "unload netcdf"
                - "unload intel.compiler"
                - "unload intel.mpi"
                - "use ~dbarbi/modulefiles"
                - "unload hdf5"
                - "load pism_externals"
                - "load proj"
            add_export_vars:
                - "I_MPI_FABRICS=shm:tmi"
                - "HDF5_ROOT=$HDF5ROOT"
                - "PROJ_ROOT=/global/AWIsoft/proj/5.1.0/"
    mistral:
        environment_changes:
            add_module_actions:
                - "unload gcc"
                - "load gcc/7.1.0"
            add_export_vars:
                - "UDUNITS2_ROOT=/pf/a/pism_build_sebastian02/local/modules/uunits2/"
                - "FFTW_ROOT=/pf/a/pism_build_sebastian02/local/modules/fftw/"
                - "PROJ4_ROOT=/pf/a/pism_build_sebastian02/local/modules/proj4/"
                - "PETSC_DIR=/pf/a/pism_build_sebastian02/local/modules/petsc-v3.12/"
                - "HDF5_ROOT=/pf/a/pism_build_sebastian02/local/modules/hdf5/"
                #- "UDUNITS2_ROOT=/sw/rhel6-x64/util/udunits-2.2.26-gcc64"
                #- "FFTW_ROOT=/sw/rhel6-x64/numerics/fftw-3.3.7-openmp-gcc64"
                #- "PROJ4_ROOT=/sw/rhel6-x64/graphics/proj4-4.9.3-gcc48"
                #- "PETSC_DIR=/sw/rhel6-x64/numerics/PETSc-3.12.2-impi2018-intel18/"
                #- "HDF5_ROOT=$HDF5ROOT"
    levante:
        #COMPILER_TAG="gcc-11.2.0"
        #COMPILER_TAG="intel-2021.5.0"
        environment_changes:
            add_module_actions:
                - "unload gcc"
                - "load intel-oneapi-compilers/2022.0.1-gcc-11.2.0"
                - "load intel-oneapi-mkl/2022.0.1-gcc-11.2.0"
                - "load openmpi/4.1.2-intel-2021.5.0"
                - "load netcdf-c/4.8.1-openmpi-4.1.2-intel-2021.5.0"
                - "load netcdf-fortran/4.5.3-openmpi-4.1.2-intel-2021.5.0"
                - "load netcdf-cxx/4.2-openmpi-4.1.2-intel-2021.5.0"
                - "load hdf5/1.12.1-openmpi-4.1.2-intel-2021.5.0"
                - "load hdf/4.2.15-intel-2021.5.0"
                - "load parallel-netcdf/1.12.2-openmpi-4.1.2-intel-2021.5.0"
                #gcc:#- "unload intel-oneapi-compilers"
                #gcc:#- "load gcc/11.2.0-gcc11.2.0"
                #gcc:#- "load openmpi/4.1.2-gcc-11.2.0"
                #gcc:#- "load netcdf-c/4.8.1-openmpi-4.1.2-gcc-11.2.0"
                #gcc:#- "load netcdf-fortran/4.5.3-openmpi-4.1.2-gcc-11.2.0"
                #gcc:#- "load netcdf-cxx/4.2-openmpi-4.1.2-gcc-11.2.0"
                #gcc:#- "load hdf5/1.12.1-openmpi-4.1.2-gcc-11.2.0"
                #gcc:#- "load hdf/4.2.15-gcc-11.2.0"
                #gcc:#- "load parallel-netcdf/1.12.2-openmpi-4.1.2-gcc-11.2.0"
            add_export_vars:
                - "UDUNITS2_ROOT=/home/a/a270096/usr/local/udunits-2.2.28-intel-2021.5.0/"
                - "FFTW_ROOT=/home/a/a270096/usr/local/fftw-3.3.10-intel-2021.5.0/"
                - "PROJ4_ROOT=/home/a/a270096/usr/local/proj-9.1.1-intel-2021.5.0/"
                - "PETSC_DIR=/home/a/a270096/usr/local/petsc-3.15.1-intel-2021.5.0/"
                #gcc:#- "UDUNITS2_ROOT=/home/a/a270096/usr/local/udunits-2.2.28-gcc-11.2.0/"
                #gcc:#- "FFTW_ROOT=/home/a/a270096/usr/local/fftw-3.3.10-gcc-11.2.0/"
                #gcc:#- "PROJ4_ROOT=/home/a/a270096/usr/local/proj-9.1.1-gcc-11.2.0/"
                #gcc:#- "PETSC_DIR=/home/a/a270096/usr/local/petsc-3.15.1-gcc-11.2.0/"
                ##- "HDF5_ROOT=/home/a/a270096/usr/local/hdf5/"
