
per_model_defaults:
        file_movements:
                default:
                        all_directions: copy
                bin:
                        init_to_exp:    copy
                        exp_to_run:     link
                        run_to_work:    link
                        work_to_run:    link

