choose_job_type:

        postprocess:
                recipe:
                        - "postprocess"

        compute:
                recipe:
                        - "_create_setup_folders"
                        - "_create_component_folders"
                        - "initialize_experiment_logfile"
                        - "_write_finalized_config"
                        - "copy_tools_to_thisrun"
                        - "_copy_preliminary_files_from_experiment_to_thisrun"
                        - "_show_simulation_info"
                        - "copy_files_to_thisrun"
                        - "modify_namelists"
                        - "modify_files"
                        - "create_new_files"
                        - "prepare_coupler_files"
                        - "add_batch_hostfile"
                        - "copy_files_to_work"
                        - "write_simple_runscript"
                        - "report_missing_files"
                        - "database_entry"
                        - "submit"
