core:
        esm_runscripts:
                compute:
                        - "_create_setup_folders"
                        - "_create_component_folders"
                        - "initialize_experiment_logfile"
                        - "_write_finalized_config"
                        - "copy_tools_to_thisrun"
                        - "_copy_preliminary_files_from_experiment_to_thisrun"
                        - "_show_simulation_info"
                        - "copy_files_to_thisrun"
                        - "modify_namelists"
                        - "modify_files"
                        - "create_new_files"
                        - "prepare_coupler_files"
                        - "add_batch_hostfile"
                        - "copy_files_to_work"
                        - "report_missing_files"

                database_actions:
                        - "database_entry"

                esm_batch_system:
                        - "write_simple_runscript"
                        - "submit"

# esm-plugins is in an early stage and has many limitations:
# 1. plugins MUST be placed in ../../esm_software/esm_runscripts/esm_plugins.yaml
#    and commented unless available
# 2. esm_plugin_manager cannot resolve variables at the moment
# 3. git-url is only for documentation purposes, if location does not 
#    exists, esm_runscripts stops with an error message
#plugins:
#        preprocess:
#                #location: ${model_dir} 
#                #location: /home/shkifmsw/gitlab/preprocess
#                location: /pf/b/b350090/esm-py/plugins/preprocess 
#                git-url: "https://github.com/esm-tools-plugins/preprocess.git"
#                preprocess:
#                        - "preprocess"
