core:
        esm_runscripts:
                compute:
                        - "_create_setup_folders"
                        - "_create_component_folders"
                        - "initialize_experiment_logfile"
                        - "_write_finalized_config"
                        - "copy_tools_to_thisrun"
                        - "_copy_preliminary_files_from_experiment_to_thisrun"
                        - "_show_simulation_info"
                        - "copy_files_to_thisrun"
                        - "modify_namelists"
                        - "modify_files"
                        - "create_new_files"
                        - "prepare_coupler_files"
                        - "add_batch_hostfile"
                        - "copy_files_to_work"

                filelists:
                        - "assemble"
                        - "report_missing_files"

                database_actions:
                        - "database_entry"

                batch_system:
                        - "write_simple_runscript"
                        - "submit"

# To add your custom plugin, see oifs.yaml, section compute_recipe, and compare to the list above.
# the custom plugin 'preprocess' listed in the compute_recipe in oifs.yaml needs to be installed beforehand with
#
# git clone https://github.com/esm-tools-plugins/preprocess
# cd preprocess
# if required activate python3 e.g. 
# module load anaconda3/bleeding_edge on
# pip install --user 
#
# now check if the plugin is available
# esm_plugins should print
# The following plugins are installed and available:
#  - preprocess
#
