components:
- rnfmap-awicm3-frontiers-frozen
- oifs-43r3-awi-frontiers-frozen
- fesom-2.0-frontiers-frozen
- oasis3mct-4.0-awicm3-frontiers-frozen
coupling_changes:
- sed -i '/COUPLENEMOECE = /s/.TRUE./.FALSE./g' oifs-43r3/src/ifs/module/yommcc.F90
- sed -i '/COUPLEFESOM2 = /s/.FALSE./.TRUE./g' oifs-43r3/src/ifs/module/yommcc.F90
- sed -i '/COUPLENEMOFOCI = /s/.TRUE./.FALSE./g' oifs-43r3/src/ifs/module/yommcc.F90

