# PISM YAML DEFAULT CONFIGURATION FILE:

model: pism
repository: https://github.com/pism/pism.git
type: ice

standalone_model: True

metadata:
        Institute: UAF and PIK
        Description:
                The Parallel Ice Sheet Model (PISM) is an open source, parallel, high-resolution ice sheet model.
        Authors: Ed Bueler, Jed Brown, Anders Levermann, Ricarda Winkelmann and many more (uaf-pism@alaska.edu)
        Publications:
                - 'Shallow shelf approximation as a "sliding law" in a thermomechanically coupled ice sheet model <https://doi.org/10.1029/2008JF001179>'
                - 'The Potsdam parallel ice sheet model (PISM-PIK) -  Part 1: Model description <https://doi.org/10.5194/tc-5-715-2011>'
        License:
                GPL 3.0

description: |
        The Parallel Ice Sheet Model (PISM) is an open source, parallel, high-resolution ice sheet model.

license_text: |
        "GPL 3.0"

available_versions:
- snowflake0.7
- snowflake1.0
- github1.1.4
- github1.2
- index1.1
choose_version:
  github1.1.4:
    branch: v1.1.4
    git-repository: https://github.com/pism/pism.git
  github1.2:
    branch: v1.2
    git-repository: https://github.com/pism/pism.git
  index1.1:
    branch: Index_dev
    git-repository: https://github.com/sebhinck/pism-pub
  snowflake0.7:
    branch: awi0.7-dev
    git-repository: swrepo1.awi.de/scmrepos/git/snowflake/snowflake.git
  snowflake1.0:
    branch: stable1.0-awi-dev
    git-repository: swrepo1.awi.de/scmrepos/git/snowflake/snowflake.git
clean_command: ${defaults.clean_command}
comp_command: "mkdir -p build; cd build; export PISM_INSTALL_PREFIX=$(readlink -f\
  \ $(pwd)/..); cmake \\\n        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \\\n        -DCMAKE_BUILD_TYPE=RelWithDebInfo\
  \ \\\n        -DPism_BUILD_TYPE=RelWithDebInfo \\\n        -DCMAKE_CXX_COMPILER=$CXX\
  \ \\\n        -DCMAKE_CXX_FLAGS=\"-std=c++11 -fp-model precise -no-fast-transcendentals\"\
  \ \\\n        -DCMAKE_C_COMPILER=$CC  \\\n        -DCMAKE_C_FLAGS=\"-fp-model precise\
  \ -no-fast-transcendentals\" \\\n        -DPETSC_EXECUTABLE_RUNS:BOOL=ON \\\n  \
  \      -DMPI_C_DIR=\"$I_MPI_ROOT\" \\\n        -DPism_USE_JANSSON:BOOL=NO \\\n \
  \       -DPism_USE_PARALLEL_NETCDF4:BOOL=OFF \\\n        -DPism_USE_PARALLEL_HDF5:BOOL=OFF\
  \ \\\n        -DPism_USE_PROJ4:BOOL=YES \\\n        -DPism_BUILD_EXTRA_EXECS:BOOL=ON\
  \ \\\n        ..; make -j4; make install;\n"


executable: pismr
version: 1.1.4
domain: "greenland"
resolution: 20km
lresume: false


model_dir: "${general.esm_master.dir}/pism-${version}"
setup_dir: "${model_dir}"
bin_dir: "${setup_dir}/bin"
pool_dir: "${computer.pool_directories.pool}/pool_pism"


choose_domain:
        "greenland":
                choose_resolution:
                        20km:
                                nx: 50
                                ny: 30
                                nz: 100


        "nhem":
                choose_resolution:
                        20km:
                                nx: 50
                                ny: 30
                                nz: 100

bin_files:
        "pism_bin": "pism_bin"
bin_sources:
        "pism_bin": "${bin_dir}/pismr"
bin_in_work:
        "pism_bin": "pismr"

further_reading:
    - pism/pism.compiletime_env_changes.yaml
