compiletime_environment_changes:
    add_module_actions:
        - "unload netcdf"
        - "unload intel.compiler"
        - "load pism_externals"
    add_export_vars:
        - "I_MPI_FABRICS=shm:tmi"
