# PISM YAML DEFAULT CONFIGURATION FILE:

model: pism
repository: https://github.com/pism/pism.git
type: ice

standalone_model: True

metadata:
        Institute: UAF and PIK
        Description:
                The Parallel Ice Sheet Model (PISM) is an open source, parallel, high-resolution ice sheet model.
        Authors: Ed Bueler, Jed Brown, Anders Levermann, Ricarda Winkelmann and many more (uaf-pism@alaska.edu)
        Publications:
                - 'Shallow shelf approximation as a "sliding law" in a thermomechanically coupled ice sheet model <https://doi.org/10.1029/2008JF001179>'
                - 'The Potsdam parallel ice sheet model (PISM-PIK) -  Part 1: Model description <https://doi.org/10.5194/tc-5-715-2011>'
        License:
                GPL 3.0

description: |
        The Parallel Ice Sheet Model (PISM) is an open source, parallel, high-resolution ice sheet model.

license_text: |
        "GPL 3.0"


# PG: BUG!! This doesn't work, but should:
#choose_computer.name:
#    ollie:
#        computer.module_actions:
#            - "load pism_externals"
#        computer.export_vars:
#            - "I_MPI_FABRICS=shm:tmi"
#    "*":
#        add_module_actions:
#            - "None"
#        add_export_vars:
#            - "None"

executable: pismr
version: 1.1.4
domain: "greenland"
resolution: 20km
lresume: false


model_dir: "${general.esm_master.dir}/pism-${version}"
setup_dir: "${model_dir}"
bin_dir: "${setup_dir}/bin"
pool_dir: "${computer.pool_directories.pool}/pool_pism"


choose_domain:
        "greenland":
                choose_resolution:
                        20km:
                                nx: 50
                                ny: 30
                                nz: 100


        "nhem":
                choose_resolution:
                        20km:
                                nx: 50
                                ny: 30
                                nz: 100

bin_files:
        "pism_bin": "pism_bin"
bin_sources:
        "pism_bin": "${bin_dir}/pismr"
bin_in_work:
        "pism_bin": "pismr"

further_reading:
    - pism/pism.compiletime_env_changes.yaml
