components:
- fesom-2.0
- recom-2.0
coupling_changes:
- sed -i '/FESOM_COUPLED/s/OFF/ON/g' fesom-2.0/CMakeLists.txt
- sed -i '/FESOM_RECOM/s/OFF/ON/g' fesom-2.0/CMakeLists.txt
- sed -i '/RECOM_LIBRARY/s/OFF/ON/g' fesom-2.0/CMakeLists.txt
