# ESM-Tests in check mode for all computers
# =========================================
# Some comments here

name: esm_tests

# Triggers the workflow on a push or a pull
on: [push, pull_request]

jobs:
  ollie:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    container:
      image: koldunovn/esm_test:latest
      options: --hostname ollie1

    # Service containers to run with `gfortran_ubuntu`
    steps:
    # NK: this changes working directory to fesom2
    - uses: actions/checkout@v2

    - name: add to the path
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: install esm-tools
      run: |
        ./install.sh
    - name: update esm_tests resources
      run: |
        esm_tests -u
    - name: run esm_tests
      run: |
        esm_tests -cn
