name: Compile Test for {{MODEL_NAME}}-{{MODEL_VERSION}}

on:
    push:
        paths:
            - '!docs/**'
            - '!README.md'
            - 'src/**'
            - 'tests/**'
            - 'configs/machines/ollie.yaml'
            - 'configs/components/{{MODEL_NAME}}/{{MODEL_NAME}}-{{MODEL_VERSION}}.yaml'

jobs:
    call-workflow:
        uses: esm-tools/esm_tools/.github/workflows/esm_tools_actions_hpc_awi_ollie.yml@monorepo_ci_test
        with:
            model_name: {{MODEL_NAME}}
            model_version: {{MODEL_VERSION}}
