name: Compile Test for fesom-1.4-esm_interface

on:
    push:
        paths:
            - '!docs/**'
            - '!README.md'
            - 'src/**'
            - 'tests/**'
            - 'configs/machines/ollie.yaml'
            - 'configs/components/fesom/*.yaml'

jobs:
    call-workflow:
        uses: esm-tools/esm_tools/.github/workflows/esm_tools_actions_hpc_awi_ollie.yml@monorepo_ci_test
        with:
            model_name: fesom
            model_version: 1.4-esm_interface