name: Tests for ECHAM Standlone

on:
    push:
        paths:
            - '!docs/**'
            - '!README.md'
            - 'src/**'
            - 'tests/**'
            - 'configs/machines/ollie.yaml'
            - 'configs/components/echam/*.yaml'
            - 'configs/components/jsbach/*.yaml'
            - 'configs/components/hdmodel/*.yaml'
            - '.github/workflows/esm_tools_echam-standalone.yml'

jobs:
    compile-ollie:
        name: Compile Test echam-standalone (Ollie)
        # Pattern for uses: github-org/repo/some/path/in/repo@commit_or_branch
        # If @commit_or_branch is ommited, github actions will break!
        # For now, I tie it to release, but there might be better ways of doing
        # that, see for instance here: https://tinyurl.com/4x6h373j
        uses: "esm-tools/esm_tools/.github/workflows/esm_tools_actions_hpc_awi_ollie.yml@release"
        secrets:
          dkrz-token: ${{ secrets.GITLAB_DKRZ_TOKEN }}
          awi-token: ${{ secrets.GITLAB_AWI_TOKEN }}
        with:
          model_name: echam
          # versions to test as a space seperated list
          model_version: "6.3.05p2 6.3.05p2-foci 6.3.02p4 6.3.04p1-esm_interface 6.3.05p2-concurrent_radiation 6.3.04p1-paleodyn 6.3.04p1-recom-awicm 6.3.05p2-concurrent_radiation-paleodyn 6.3.04p1 6.3.05p2-wiso"
