name: esm-tools main test

# Controls when the action will run. Triggers the workflow on push or pull request.

on: [push, pull_request]

jobs:
  basic_tests:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    container: koldunovn/esm_test:latest

    # Service containers to run with `gfortran_ubuntu`
    steps:
    # NK: this changes working directory to fesom2
    - uses: actions/checkout@v2
    
    - name: add to the path
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: install esm-tools
      run: |
        ./install.sh
        
    - name: run esm_master first time
      run: |    
        yes Y | esm_master
    
    - name: run esm_master second time
      run: |    
        esm_master
        
