name: esm-tools Ollie

# Reusuable part
on:
    workflow_call:
        inputs:
            model_name:
                required: True
                type: string
            model_version:
                required: True
                type: string
        secrets:
            dkrz-token:
                required: True
            awi-token:
                required: True


defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
    setup_version_matrix:
        runs-on: hpc_awi_ollie
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
          - name: Download Code
            uses: actions/checkout@v2
          - id: test-set-matrix
            run: echo "..set-output name=matrix..$(python utils/versions_to_json_matrix.py ${{inputs.model_version}})"
          - id: set-matrix
            run: echo "::set-output name=matrix::$(python utils/versions_to_json_matrix.py ${{inputs.model_version}})"
    basic_compile_test:
        needs: setup_version_matrix
        runs-on: hpc_awi_ollie
        strategy:
            matrix: ${{fromJSON(needs.split_string.outputs.matrix)}}
        env:
            LC_ALL: en_US.UTF-8
            LANG: en_US.UTF-8

        steps:
          - name: Download Code
            uses: actions/checkout@v2

          - name: Add to the path
            run: |
              echo "$HOME/.local/bin" >> $GITHUB_PATH

          - name: Install esm-tools
            run: |
              module load git
              module load python3
              ./install.sh

          - name: Create esmtoolsrc file
            run: |
                echo GITLAB_DKRZ_USER_NAME=${{ secrets.dkrz-token }} >> ${HOME}/.esmtoolsrc
                echo SWREPO_AWI_USER_NAME=${{ secrets.awi-token }} >> ${HOME}/.esmtoolsrc

          - name: Run esm_master
            run: |
              esm_master

          - name: Run esm_plugins
            run: |
              esm_plugins

          - name: Run get-${{ inputs.model_name }}-${{ matrix.version }}
            run: |
              esm_master get-${{ inputs.model_name }}-${{ matrix.version }}

          - name: Run status-${{ inputs.model_name }}-${{ matrix.version }}
            run: |
              esm_master status-${{ inputs.model_name }}-${{ matrix.version }}

          - name: Run comp-${{ inputs.model_name }}-${{ matrix.version }}
            run: |
                esm_master comp-${{ inputs.model_name }}-${{ matrix.version }}

          - name: Run clean-${{ inputs.model_name }}-${{ matrix.version }}
            run: |
              esm_master clean-${{ inputs.model_name }}-${{ matrix.version }}

          - name: Clean up
            if: ${{ always() }}
            run: |
                rm -rf ${HOME}/.esmtoolsrc ${HOME}/.esm_tools
